### ISSUE TITLE
Directory/path to a domain/feature

### ISSUE THREAD

**Issue by vladimirdrayling** [angular-architects/nx-ddd-plugin#12]
# Feature request

### Initial situation

Currently a cannot extend the path to domain/feature like this: `web/expert`.

![image](https://user-images.githubusercontent.com/16114644/87229641-07be7380-c3aa-11ea-9825-c0d09cefbe87.png)

### Given

Empty `libs` folder. The workspace could contain multiple apps for different platforms (web, nativescript, ionic, electron etc.).

### Solution

I could image two possible solutions:

* Second input for `directory`
* replace `/` with `-` to generate a name

In the end we would have a more flexible way to organize the libs folder:

```yaml
libs:
  web:
    admin:
      domain
      feature
  mobile:
    some-folder:
      domain
      feature
  desktop:
```
