### ISSUE TITLE
Ambiguous modules/modules with same names

### ISSUE THREAD

**Issue by vladimirdrayling** [angular-architects/nx-ddd-plugin#13]
By generating domains I get this folder structure:

```yml
libs:
  company:
    domain:
      src:
        lib:
          domain.module.ts
        index.ts
        ...
  expert:
    domain:
      src:
        lib:
          domain.module.ts
        index.ts
        ...
```

Then I wanna import company and expert "modules". There're at least two ways to import:
* Lazy (import in router module with `import()`
* Non lazy

There is no problem with the lazy approach but with non lazy:

```ts
import { DomainModule as ExpertModule } from '@workspace/expert/domain';
import { DomainModule as CompanyModule } from '@workspace/company/domain';

@NgModule({
  imports: [
    ExpertModule,
    CompanyModule,
  ]
})
...
```

In the sample above I need to use aliases `as ExpertModule` and `as CompanyModule` to be able to import both modules with the identical class name. We, devs, are pretty lazy and that approach compels us to add an extra alias for every lib/module name.

What about class names that match the names passed in while generating a lib?
